name: Run on Windows

on:
  workflow_dispatch:

jobs:
  windows-job:
    runs-on: windows-latest # 或者 windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Windows commands
        run: |
          echo "Running on Windows Server (compatible with Windows 11)"
          systeminfo
          dir
        shell: powershell
