name: ZeroTier SSH

on:
  workflow_dispatch: # 手动触发

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo mkdir /run/sshd
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          echo "root:github123" | sudo chpasswd
          sudo service ssh start

      - name: Install ZeroTier
        run: |
          curl -s https://install.zerotier.com | sudo bash
          sudo zerotier-cli join 8bd5124fd6462eb6
          sleep 10
          sudo zerotier-cli listpeers

      - name: Display ZeroTier IP
        run: |
          sudo zerotier-cli listnetworks | grep -oP '10\.\d+\.\d+\.\d+'
